server:
  port: 8080
#数据库源
spring:
  datasource:
    url: jdbc:mysql://10.160.0.20:3306/asd_analysis
    username: liukai
    password: liukai
    driver-class-name: com.mysql.jdbc.Driver
#mybatis
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.aisidi.analysis.core.model
