server:
  port: 8989
#数据库源
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/asd_analysis
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#mybatis
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.aisidi.analysis.core.model

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  
logging:
  level:
    com.aisidi.analysis.core.mapper: debug